[features]
seeds = false
skip-lint = false
[programs.localnet]
test_anchor = "Ec2mfjaAxxBYvtEKwK1i9tdgGm5xog5gDn5nLKmhDBFU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
